# Text Generation

* 시점별로, 준비된 단어들 중 어떤 단어를 가져와야 적절할지 '선택'하는 문제이다.
* 선택이란 곧, 분류이다.( 적절한 선택 or 그렇지 않은 선택들 )
* 당연히, 데이터가 엄청 많아야 '작사'다울 수 있다.
* 데이터가 부족한 지금은, 모델은 고장난 앵무새일 수 밖에 없다.

# Data : 야생화, 바람기억, 숨

**조건**
1. 원하는 노래가사로 변경해도 좋다. 하지만 아래의 포맷을 맞추어 내야 코드를 재사용할 수 있다.


In [1]:
# 처음 설치할때만 실행하고, 그 후에는 주석처리 하세요.
!pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 35.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.3/465.3 KB 24.3 MB/s eta 0:00:00


In [47]:
import numpy as np
import pandas as pd

In [48]:
gasa1 = "하얗게 피어난 얼음 꽃 하나가\n달가운 바람에 얼굴을 내밀어\n아무 말 못했던 이름도 몰랐던\n지나간 날들에 눈물이 흘러\n차가운 바람에 숨어 있다\n한줄기 햇살에 몸 녹이다\n그렇게 너는 또 한번 내게 온다\n좋았던 기억만\n그리운 마음만\n니가 떠나간 그 길 위에\n이렇게 남아 서 있다\n잊혀질 만큼만\n괜찮을 만큼만\n눈물 머금고 기다린 떨림 끝에\n다시 나를 피우리라\n사랑은 피고 또 지는 타버리는 불꽃\n빗물에 젖을까 두 눈을 감는다\n어리고 작았던 나의 맘에\n눈부시게 빛나던 추억 속에\n그렇게 너를 또 한번 불러본다\n좋았던 기억만\n그리운 마음만\n니가 떠나간 그 길 위에\n이렇게 남아 서 있다\n잊혀질 만큼만\n괜찮을 만큼만\n눈물 머금고 기다린 떨림\n끝에 다시 나는\n메말라가는 땅 위에\n온몸이 타 들어가고\n내 손끝에 남은\n너의 향기 흩어져 날아가\n멀어져 가는 너의 손을\n붙잡지 못해 아프다\n살아갈 만큼만\n미워했던 만큼만\n먼 훗날 너를 데려다 줄\n그 봄이 오면\n그날에 나 피우리라"
gasa2 = """바람 불어와 내 맘 흔들면
지나간 세월에
두 눈을 감아본다
나를 스치는 고요한 떨림
그 작은 소리에
난 귀를 기울여 본다
내 안에 숨쉬는
커버린 삶의 조각들이
날 부딪혀 지날 때
그 곳을 바라보리라
우리의 믿음 우리의 사랑
그 영원한 약속들을
나 추억한다면 힘차게 걸으리라
우리의 만남 우리의 이별
그 바래진 기억에
나 사랑했다면 미소를 띄우리라
내 안에 있는
모자란 삶의 기억들이
날 부딪혀 지날 때
그 곳을 바라보리라
우리의 믿음 우리의 사랑
그 영원한 약속들을
나 추억한다면 힘차게 걸으리라
우리의 만남 우리의 이별
그 바래진 기억에
나 사랑했다면 미소를 띄우리라"""
gasa3 = "오늘 하루 쉴 숨이\n오늘 하루 쉴 곳이\n오늘만큼 이렇게 또 한번 살아가\n침대 밑에 놓아둔\n지난 밤에 꾼 꿈이\n지친 맘을 덮으며\n눈을 감는다 괜찮아\n남들과는 조금은 다른 모양 속에\n나 홀로 잠들어\n다시 오는 아침에\n눈을 뜨면 웃고프다\n오늘 같은 밤\n이대로 머물러도 될 꿈이라면\n바랄 수 없는걸 바라도 된다면\n두렵지 않다면 너처럼\n오늘 같은 날\n마른 줄 알았던\n오래된 눈물이 흐르면\n잠들지 않는 내 작은 가슴이\n숨을 쉰다\n끝도 없이 먼 하늘\n날아가는 새처럼\n뒤돌아 보지 않을래\n이 길 너머 어딘가 봄이\n힘없이 멈춰있던\n세상에 비가 내리고\n다시 자라난 오늘\n그 하루를 살아\n오늘 같은 밤\n이대로 머물러도 될 꿈이라면\n바랄 수 없는걸 바라도 된다면\n두렵지 않다면 너처럼\n오늘 같은 날\n마른 줄 알았던\n오래된 눈물이 흐르면\n잠들지 않는\n이 어린 가슴이 숨을 쉰다\n고단했던 내 하루가\n숨을 쉰다"

In [49]:
gasa1_ = gasa1.split("\n")
gasa2_ = gasa2.split("\n")
gasa3_ = gasa3.split("\n")

gasa = gasa1_ + gasa2_ + gasa3_

In [50]:
from konlpy.tag import Okt
okt = Okt()

# 이랬던 문장이.
print("원본 문장 : ", gasa[1]) 

# 이렇게 바뀝니다. okt.morphs가 형태소 분석기에요.
형태소토큰 = okt.morphs(gasa[1])
print("형태소 기준으로 tokenize : ", 형태소토큰) 

# 이러면 배운 대로, 띄어쓰기 기준 token을 사용할 수 있겠죠?
다시문장으로 = " ".join(형태소토큰)
print("다시 문장으로 : ", 다시문장으로)

원본 문장 :  달가운 바람에 얼굴을 내밀어
형태소 기준으로 tokenize :  ['달', '가운', '바람', '에', '얼굴', '을', '내밀어']
다시 문장으로 :  달 가운 바람 에 얼굴 을 내밀어


# Q1. gasa안의 모든 문장에, 형태소 사이 사이에 띄어쓰기를 추가하라.

**힌트**
1. 위의 코드를 적극 참고할 것.
2. 루프

In [51]:
####################
## Your Code here ##
####################
X = []
for g in gasa:
    X.append(' '.join(okt.morphs(g)))

X[:3]

['하얗게 피어 난 얼음 꽃 하나 가', '달 가운 바람 에 얼굴 을 내밀어', '아무 말 못 했던 이름 도 몰랐던']

# Q2. gasa를 띄어쓰기 기준으로 tokenize하고, index의 sequence로 바꾸어 내시오.

**조건**
0. gasa_seq에, index의 seq로 바뀐 가사를 선언해둔다.
1. 데이터가 부족하다, 모든 단어 다 사용할 것.
2. vocab_size라는 변수에 사용하게 될 token의 수를 선언해두자.
    * 힌트1 : 토크나이저.index_word , 인덱스가 몇부터 시작하는가?
    * 힌트2 : 패딩, 0을 덧댈것이다. (0이 인덱스이자 덧댐을 의미하는 token이 될 것이다.)
    * 힌트3 : embedding 때도, index:0이 필요하다.
    * 힌트4 : 원핫인코딩도, 0부터 시작하기 때문에, 0이 필요하다.
    * 힌트5 : 심지어, Tokenizer도, num_words = 1000을 둔다면, 상위 999개 token만 사용한다. (우리가 0을 추가로 사용할 것을 가정함. 결국 1000개가 됨.)

In [52]:
####################
## Your Code here ##
####################
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(lower=False)

In [53]:
%%time
tokenizer.fit_on_texts(X)
gasa_seq = tokenizer.texts_to_sequences(X)

CPU times: user 1.85 ms, sys: 0 ns, total: 1.85 ms
Wall time: 2.11 ms


In [106]:
vocab_size = len(tokenizer.index_word) + 1

# Q3. gasa_seq안의 모든 문장을 다음과 같이 재구성하시오.

**예시**
* gasa_seq가 [ [1,2,3], [7,2,9,10] ] 라면
* 결과 : gasa_seq = [ [1, 2], [1,2,3], [7,2], [7,2,9], [7,2,9,10] ]
* 중간에 다른 변수를 임시로 사용해도 좋다.

In [56]:
gasa_seq[:5]

[[110, 111, 43, 112, 113, 114, 14],
 [115, 116, 26, 1, 117, 3, 118],
 [119, 120, 44, 45, 121, 46, 122],
 [47, 15, 10, 1, 16, 2, 123],
 [124, 26, 1, 125, 27]]

In [61]:
####################
## Your Code here ##
####################
temp = []
max_len = 0
for g in gasa_seq:
    max_len = max(max_len, len(g))
    for i in range(1, len(g)):
        temp.append(np.array(g[:i + 1]))
temp[:5], max_len

([array([110, 111]),
  array([110, 111,  43]),
  array([110, 111,  43, 112]),
  array([110, 111,  43, 112, 113]),
  array([110, 111,  43, 112, 113, 114])],
 9)

In [62]:
gasa_seq = temp

# Q4. gasa_seq안의 가장 긴 문장을 찾고, 그 길이에 맞추어 문장 길이를 통일하시오.

**Questions**
1. 0을 앞에 덧대야 할까, 뒤에 덧대야 할까?
2. 문장의 길이가 매우 길다면, 가장 긴 문장에 맞추어 길이를 통일하는 것이 좋은 방법일까?
3. gasa_seq의 shape를 확인하라.

In [63]:
####################
## Your Code here ##
####################
from tensorflow.keras.preprocessing.sequence import pad_sequences

gasa_seq = pad_sequences(gasa_seq, maxlen=max_len, padding='pre')

gasa_seq.shape

(382, 9)

# Q5. gasa_seq의 마지막 컬럼은 y로, 나머지 컬럼은 x로 분할하라.

In [67]:
####################
## Your Code here ##
####################

x = gasa_seq[:, :-1]
y = gasa_seq[:, -1]

# Q6. y를, vocab_size에 맞추어 원핫 인코딩 하시오.

1. num_classes 를 반드시 vocab_size에 맞출 것.
2. 사용하지 않을 컬럼이 존재할 수 있다.
    * 예시) y에는 4가 없는데, 0으로만 가득찬 4번 컬럼이 만들어질 수도 있다.

**추가설명**
* 효율을 위해, 이 모든걸 엄격히 보정하여 사용할 수도 있다.
* 그러나, 코드가 매우 길어진다.
* 데이터가 많아지면, 별차이도 없어진다.

In [69]:
####################
## Your Code here ##
####################
from tensorflow.keras.utils import to_categorical

y = to_categorical(y, num_classes=vocab_size)

# Q7. 문장을 받아, 다음 단어를 선택하는 모델을 만드시오.

* 컴파일까지 마치시오.
    * 모니터링 지표로 accuracy 사용0
* 모델 구조는 아래와 같다.
    1. 임베딩 레이어 : 임베딩 차원 32, input_length 주의. gasa_seq를 x와 y로 분할했기 때문에, 문장길이가 달라졌다.
    2. GRU, 32, 모든 출력을 다음 layer로
    3. GRU, 48, 모든 출력을 다음 layer로
    4. GRU, 64, 마지막 출력만 다음 레이어로.
    5. 멀티클래스 분류 아웃풋레이어


In [76]:
####################
## Your Code here ##
####################
import tensorflow as tf
from tensorflow import keras
import tensorflow.keras.backend as K
from tensorflow.keras.layers import Input, Dense, Flatten, Conv1D, MaxPool1D
from tensorflow.keras.layers import GRU, Embedding
from tensorflow.keras.models import Model

In [73]:
x.shape

(382, 8)

In [77]:
####################
## Your Code here ##
####################

# 세션 클리어
K.clear_session()

# 모델 쌓기
# 0. Input
il = Input(shape=(max_len - 1))

# 1. 임베딩 레이어 : 임베딩 차원 32, input_length 주의. gasa_seq를 x와 y로 분할했기 때문에, 문장길이가 달라졌다.
hl = Embedding(vocab_size, 32, input_length=max_len - 1)(il)

# 2. GRU, 32, 모든 출력을 다음 layer로
hl = GRU(32, return_sequences=True)(hl)
# 3. GRU, 48, 모든 출력을 다음 layer로
hl = GRU(48, return_sequences=True)(hl)
# 4. GRU, 64, 마지막 출력만 다음 레이어로.
hl = GRU(64, return_sequences=False)(hl)
# 5. 멀티클래스 분류 아웃풋레이어
ol = Dense(vocab_size, activation='softmax')(hl)

# 모델 선언
model = Model(il, ol)

# 컴파일
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

# 요약
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 8)]               0         
                                                                 
 embedding (Embedding)       (None, 8, 32)             7200      
                                                                 
 gru (GRU)                   (None, 8, 32)             6336      
                                                                 
 gru_1 (GRU)                 (None, 8, 48)             11808     
                                                                 
 gru_2 (GRU)                 (None, 64)                21888     
                                                                 
 dense (Dense)               (None, 225)               14625     
                                                                 
Total params: 61,857
Trainable params: 61,857
Non-trainable p

# Q8. 모델을 학습시킬 것.

* batch_size = 64
* epochs = 1000


In [78]:
####################
## Your Code here ##
####################
history = model.fit(x, y, epochs=1000, batch_size=64)

Epoch 1/1000
6/6 [==============================] - 15s 161ms/step - loss: 5.4145 - accuracy: 0.0340
Epoch 2/1000
6/6 [==============================] - 1s 131ms/step - loss: 5.4007 - accuracy: 0.0654
Epoch 3/1000
6/6 [==============================] - 1s 99ms/step - loss: 5.3713 - accuracy: 0.0654
Epoch 4/1000
6/6 [==============================] - 0s 8ms/step - loss: 5.2955 - accuracy: 0.0654
Epoch 5/1000
6/6 [==============================] - 0s 7ms/step - loss: 5.0981 - accuracy: 0.0654
Epoch 6/1000
6/6 [==============================] - 0s 39ms/step - loss: 5.0484 - accuracy: 0.0654
Epoch 7/1000
6/6 [==============================] - 0s 8ms/step - loss: 4.9788 - accuracy: 0.0654
Epoch 8/1000
6/6 [==============================] - 0s 8ms/step - loss: 4.9305 - accuracy: 0.0654
Epoch 9/1000
6/6 [==============================] - 0s 70ms/step - loss: 4.9174 - accuracy: 0.0654
Epoch 10/1000
6/6 [==============================] - 0s 38ms/step - loss: 4.9041 - accuracy: 0.0654
Epoch 11/1

# Q9. 학습된 모델을 이용하여, '나'뒤에 생성될 확률이 가장 높은 3개 단어를 출력하시오.

1. first_word = ['나'] 을 활용한다.
1. 인풋은 똑같은 전처리 과정을 겪어야 한다. (단, 문장 길이는 max_len -1 일것이다. )
2. 아웃풋은, 가장 출력값이 큰 3개의 index를 찾아낼 수 있어야 한다.
    * np.argsort를 활용해볼 것
3. 아웃풋의 index가 정확히 어떤 단어를 가리키는지, 토크나이저의 index_word를 활용하여 복원한다.
4. 이후에 나올 단어 3개와, 확률을 print를 이용하여 같이 출력한다.

In [104]:
####################
## Your Code here ##
####################

first_word = ['나']
temp = tokenizer.texts_to_sequences(first_word)
temp = pad_sequences(temp, maxlen=max_len - 1, padding='pre')

y_pred = model.predict(temp)

top3_idx = np.argsort(y_pred)[:, -3:].reshape(-1)[::-1]
top3_probs = y_pred[:, top3_idx].reshape(-1)

for i in range(3):
    word = tokenizer.index_word[top3_idx[i]]
    prob = top3_probs[i]
    print(f'{word} : {prob * 100:.2f}')

1/1 [==============================] - 0s 23ms/step
추억 : 40.35
사랑 : 38.91
홀로 : 18.71


# Q10. 위의 Q9에서 두번째로 확률이 높은 단어를 골라 문장을 구성한 뒤, 다음에 올 단어로 가장 확률이 높은 3 단어를 출력하시오.

1. 만일, 가장 확률 높은 단어가 '추억'이었다면, words = '나 추억' 을 활용한다.
1. 확률과 단어를 같이 출력한다.
2. 기본적으로는 위 Q9번과 동일하게 푼다.

In [105]:
####################
## Your Code here ##
####################

first_word = ['나 추억']
temp = tokenizer.texts_to_sequences(first_word)
temp = pad_sequences(temp, maxlen=max_len - 1, padding='pre')

y_pred = model.predict(temp)

top3_idx = np.argsort(y_pred)[:, -3:].reshape(-1)[::-1]
top3_probs = y_pred[:, top3_idx].reshape(-1)

for i in range(3):
    word = tokenizer.index_word[top3_idx[i]]
    prob = top3_probs[i]
    print(f'{word} : {prob * 100:.2f}')

1/1 [==============================] - 0s 23ms/step
한다면 : 99.45
않다면 : 0.18
너 : 0.12


# Q11. 9번,10번 문항을 참고하여, 다음의 기능을 하는 함수를 제작한다.

* 편의를 위해, 외부에 선언된 변수를 활용해도 좋다.
* 인풋 : 사용할 첫 단어, 반복 예측 수
* 내부 : 매번 가장 확률 높은 단어만 선택한다.
* 아웃풋 : 완성된 문장.
* 예시 :
```
jaksa("나", 4 )
>> "나 추억 한다면 힘차게 걸으리라"
```
* 실제로 노래 가사에 사용된 여러 단어를 넣어 테스트해보자.

In [118]:
####################
## Your Code here ##
####################
def jaksa(first_word, n):
    first_word = [first_word]
    for i in range(n):
        temp = tokenizer.texts_to_sequences(first_word)
        temp = pad_sequences(temp, maxlen=max_len - 1, padding='pre')

        y_pred = model.predict(temp, verbose=0)
        word = tokenizer.index_word[np.argmax(y_pred)]
        first_word.append(word)
        first_word = [' '.join(first_word)]
    return first_word[0]

In [120]:
#######################
## Your testing here ##
#######################

jaksa("나", 4)

'나 추억 한다면 힘차게 걸으리라'

# (+Optional)Q12. Q11번 함수를 개량하여 다듬는다.

* 인풋 : 사용할 첫 단어, 반복 예측 수, 사용할 모델, 사용할 tokenizer
* 내부 : 모든 예측 중 하나를 확률에 맞추어 sampling 한다.
    * np.random.choice 이용. 만일 '바람'일 확률이 80%라면, 100번에 80번 정도는 바람이, 20번 정도는 다른 단어가 선택될 것이다.
* 아웃풋 : 완성된 문장.
* 반복 예측 수 : 7이상이면 다음의 문구를 출력하고 함수 동작을 종료한다.
    * "6이하의 반복예측만 가능합니다."
* 예시 :
```
jaksa("나", 4, tk, model )
>> "나 추억 한다면 힘차게 걸으리라"
jaksa("나", 4, tk, model )
>> "나 사랑 했다면 미소 를"
```

In [138]:
####################
## Your Code here ##
####################
def jaksa(first_word, n, tk, model):
    if n >= 7:
        print('6이하의 반복예측만 가능합니다.')
        return
    first_word = [first_word]
    for i in range(n):
        temp = tk.texts_to_sequences(first_word)
        temp = pad_sequences(temp, maxlen=max_len - 1, padding='pre')

        y_pred = model.predict(temp, verbose=0)

        top3_idx = np.argsort(y_pred)[:, -3:].reshape(-1)[::-1]
        top3_probs = y_pred[:, top3_idx].reshape(-1)
        idx = np.random.choice(top3_idx, p=(top3_probs + ((1 - top3_probs.sum()) / 3))) # 확률적으로 top3 에서 index 뽑기
        word = tk.index_word[idx]
        first_word.append(word)
        first_word = [' '.join(first_word)]
    return first_word[0]

In [140]:
#######################
## Your testing here ##
#######################

jaksa("나", 4, tokenizer, model)

'나 사랑 했다면 미소 를'

In [141]:
jaksa("나", 4, tokenizer, model)

'나 추억 한다면 힘차게 걸으리라'

In [142]:
jaksa("나", 4, tokenizer, model)

'나 홀로 잠들어 해 아프다'

In [156]:
jaksa("그", 4, tokenizer, model)

'그 영원한 약속 들 을'

In [162]:
jaksa("그", 4, tokenizer, model)

'그 바 래 진 기억'