# 데이터 선택
## 넘파이 실습

In [1]:
# 라이브러리 로딩
import numpy as np

In [3]:
# 파이썬 리스트에서 넘파이로 변환
a = [1, 3.14, True, 'hello'] # 리스트
b = np.array(a)

In [4]:
print(a)
for element in a:
    print('Data type of {} : {}'.format(element, type(element)))

[1, 3.14, True, 'hello']
Data type of 1 : <class 'int'>
Data type of 3.14 : <class 'float'>
Data type of True : <class 'bool'>
Data type of hello : <class 'str'>


In [5]:
print(b)
for element in b:
    print('Data type of {} : {}'.format(element, type(element)))

['1' '3.14' 'True' 'hello']
Data type of 1 : <class 'numpy.str_'>
Data type of 3.14 : <class 'numpy.str_'>
Data type of True : <class 'numpy.str_'>
Data type of hello : <class 'numpy.str_'>


In [6]:
# 중첩 리스트 생성
a = [[1, 2, 3], [4, 5, 6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [7]:
type(a)

list

In [8]:
# 중첩리스트를 넘파이 배열로 변환
b = np.array(a)
print(b)
type(b)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [9]:
b.shape

(2, 3)

In [10]:
b.ndim

2

In [11]:
b.size

6

In [12]:
print(b.reshape(3, 2))

[[1 2]
 [3 4]
 [5 6]]


In [13]:
# 배열 요소 데이터타입 변경 : 정수 -> 실수
b = np.array(a, dtype=np.float64)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [14]:
# 배열 요소 데이터타입 변경 : 실수 -> 정수
b = b.astype(np.int64)
print(b)

[[1 2 3]
 [4 5 6]]


## 넘파이 배열 인덱싱

In [15]:
# 새로운 배열 arr 생성
arr = np.array([1, 2, 3, 4, 5])

In [16]:
print(arr)

[1 2 3 4 5]


In [17]:
print(arr[0])

1


In [19]:
print(arr[3])

4


In [20]:
print(arr[-1])

5


### 2차원 배열 인덱싱

In [24]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [25]:
arr_2d[0, 0]

1

In [26]:
arr_2d[1, 2]

6

### 배열 슬라이싱

In [27]:
arr_2d = np.arange(1, 7).reshape(2, 3)
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [28]:
print(arr_2d[0, :])

[1 2 3]


In [29]:
print(arr_2d[:, 2])

[3 6]


In [30]:
print(arr_2d[:, :2])

[[1 2]
 [4 5]]


## 판다스 실습

In [31]:
import pandas as pd

### 데이터 생성

In [32]:
data = {
    '이름' : ['아이유', '김연아', '홍길동', '장범준', '강감찬'],
    '학과' : ['국문학', '수학', '컴퓨터', '철학', '경영학'],
    '성적' : [3.0, 1.0, 3.5, 2.7, 4.0]
}

In [33]:
data

{'이름': ['아이유', '김연아', '홍길동', '장범준', '강감찬'],
 '학과': ['국문학', '수학', '컴퓨터', '철학', '경영학'],
 '성적': [3.0, 1.0, 3.5, 2.7, 4.0]}

In [34]:
# 딕셔너리 타입인 data를 pd.DataFrame() 인자로 넣어주면 됨
df = pd.DataFrame(data)

display(df)

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

### 데이터 csv로 저장하기

In [36]:
df.to_csv('./data/student.csv', sep=',', index=False)

### 데이터 불러오기

In [37]:
df = pd.read_csv('./data/student.csv')
display(df)

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

### 판다스 원하는 데이터 선택하기
#### 1) 슬라이싱 (slicing)

In [38]:
df[1:5]

이름   학과   성적
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [39]:
df[0:3]

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5

In [40]:
df[0:]

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [42]:
df[:]

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

#### 2) 인덱싱(indexing)

In [44]:
df[1] # key error가 뜬다.

KeyError: 1

In [45]:
df['이름']

0    아이유
1    김연아
2    홍길동
3    장범준
4    강감찬
Name: 이름, dtype: object

In [46]:
df['학과']

0    국문학
1     수학
2    컴퓨터
3     철학
4    경영학
Name: 학과, dtype: object

#### 3) Fancy Indexing

In [47]:
df[['이름', '학과']]

이름   학과
0  아이유  국문학
1  김연아   수학
2  홍길동  컴퓨터
3  장범준   철학
4  강감찬  경영학

In [48]:
fancy_list = ['이름', '학과']
df[fancy_list]

이름   학과
0  아이유  국문학
1  김연아   수학
2  홍길동  컴퓨터
3  장범준   철학
4  강감찬  경영학

#### 4) 슬라이싱 + 인덱싱

In [49]:
df[1:3][['학과', '이름']]

학과   이름
1   수학  김연아
2  컴퓨터  홍길동

In [50]:
df[['학과', '이름']][1:3]

학과   이름
1   수학  김연아
2  컴퓨터  홍길동

#### 5) Boolean indexing
연산자를 이용하여 인덱싱 수행 e.g. `==, !=, >`, etc)

In [51]:
df[df['학과'] == '수학']

이름  학과   성적
1  김연아  수학  1.0

In [52]:
df

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [53]:
df [df['성적'] % 0.5 == 0]

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
4  강감찬  경영학  4.0

In [54]:
df['성적'] % 0.5 == 0

0     True
1     True
2     True
3    False
4     True
Name: 성적, dtype: bool

#### 6) pandas 고급 인덱싱 `loc` % `iloc` 인덱서

In [55]:
df.loc[3]

이름    장범준
학과     철학
성적    2.7
Name: 3, dtype: object

In [56]:
df

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [58]:
df.loc[[1, 3, 4]]

이름   학과   성적
1  김연아   수학  1.0
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [59]:
df.loc[ [1, 3, 4], :]

이름   학과   성적
1  김연아   수학  1.0
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [60]:
df.loc[ [1, 3, 4], '이름':'성적']

이름   학과   성적
1  김연아   수학  1.0
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [61]:
df.loc[ [1, 3, 4], '이름':'학과']

이름   학과
1  김연아   수학
3  장범준   철학
4  강감찬  경영학

In [63]:
df.loc[ [1, 3, 4], ['이름','학과']]

이름   학과
1  김연아   수학
3  장범준   철학
4  강감찬  경영학

In [64]:
df.iloc[[1, 3, 4], 0:2]

이름   학과
1  김연아   수학
3  장범준   철학
4  강감찬  경영학

In [66]:
# loc + boolean indexing
df.loc[ df['성적'] % 2 != 0, ['이름', '학과', '성적']]

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7

In [67]:
df.loc[ df['성적'] % 2 != 0, ['이름', '성적']]

이름   성적
0  아이유  3.0
1  김연아  1.0
2  홍길동  3.5
3  장범준  2.7