# Keras로 Linear&Logistic Regression 맛보기!
---
#### 실습목표
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [2]:
x = np.array(range(20))
y = x * 2 - 1 

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [3]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

## 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,)) )

# 4번 컴파일 
model.compile(loss='mse',
              optimizer='adam')

In [4]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 898ms/step - loss: 1218.0924
Epoch 2/10
1/1 [==============================] - 0s 12ms/step - loss: 1217.2577
Epoch 3/10
1/1 [==============================] - 0s 13ms/step - loss: 1216.4235
Epoch 4/10
1/1 [==============================] - 0s 12ms/step - loss: 1215.5895
Epoch 5/10
1/1 [==============================] - 0s 10ms/step - loss: 1214.7556
Epoch 6/10
1/1 [==============================] - 0s 14ms/step - loss: 1213.9222
Epoch 7/10
1/1 [==============================] - 0s 17ms/step - loss: 1213.0892
Epoch 8/10
1/1 [==============================] - 0s 13ms/step - loss: 1212.2565
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 1211.4241
Epoch 10/10
1/1 [==============================] - 0s 10ms/step - loss: 1210.5918


In [5]:
print(y)

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [6]:
model.predict(x).reshape(-1)

1/1 [==============================] - 0s 142ms/step


array([ 9.9987797e-03, -1.1971350e+00, -2.4042687e+00, -3.6114025e+00,
       -4.8185363e+00, -6.0256701e+00, -7.2328038e+00, -8.4399376e+00,
       -9.6470718e+00, -1.0854206e+01, -1.2061339e+01, -1.3268473e+01,
       -1.4475607e+01, -1.5682741e+01, -1.6889874e+01, -1.8097008e+01,
       -1.9304142e+01, -2.0511276e+01, -2.1718410e+01, -2.2925543e+01],
      dtype=float32)

## Now, Your turn!

In [7]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [10]:
x = np.array(range(20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [11]:
x.shape, y.shape

((20,), (20,))

In [12]:
## 모델링 : Sequential API
# 1. 세션 클리어 : 기존의 모델이 메모리에 남아있다면 지워줘
keras.backend.clear_session()

# 2. 모델을 쌓을 발판 생성
model = keras.models.Sequential()

# 3. 모델 블록 조립
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1))

# 4. 모델 컴파일
model.compile(loss='mse', optimizer='adam')

In [13]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 424ms/step - loss: 368.2115
Epoch 2/10
1/1 [==============================] - 0s 14ms/step - loss: 367.7749
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 367.3385
Epoch 4/10
1/1 [==============================] - 0s 19ms/step - loss: 366.9025
Epoch 5/10
1/1 [==============================] - 0s 12ms/step - loss: 366.4667
Epoch 6/10
1/1 [==============================] - 0s 15ms/step - loss: 366.0312
Epoch 7/10
1/1 [==============================] - 0s 14ms/step - loss: 365.5961
Epoch 8/10
1/1 [==============================] - 0s 11ms/step - loss: 365.1613
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: 364.7268
Epoch 10/10
1/1 [==============================] - 0s 10ms/step - loss: 364.2926


In [15]:
y_pred = model.predict(x)
y_pred.reshape(-1)

1/1 [==============================] - 0s 53ms/step


array([-9.9973278e-03, -5.8839583e-01, -1.1667944e+00, -1.7451930e+00,
       -2.3235915e+00, -2.9019899e+00, -3.4803886e+00, -4.0587869e+00,
       -4.6371856e+00, -5.2155843e+00, -5.7939825e+00, -6.3723812e+00,
       -6.9507799e+00, -7.5291781e+00, -8.1075764e+00, -8.6859751e+00,
       -9.2643738e+00, -9.8427725e+00, -1.0421171e+01, -1.0999569e+01],
      dtype=float32)

In [16]:
y

array([ 10,   7,   4,   1,  -2,  -5,  -8, -11, -14, -17, -20, -23, -26,
       -29, -32, -35, -38, -41, -44, -47])

## Quick Logistic Regression!

In [17]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [18]:
x = np.array(range(20)) 
y = np.array([0]*10 + [1]*10)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [19]:
x.shape, y.shape

((20,), (20,))

In [20]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# model에 순차적으로 레이어를 쌓아가겠다는 의도!
model = keras.models.Sequential()

# model에 인풋 값을 받는 레이어를 넣음
model.add( keras.layers.Input(shape=(1,)) )
# model에 Dense 레이어를 넣을거야 (최초의 레이어) : weight를 곱하고, bias를 더해주는 과정
model.add( keras.layers.Dense(1, activation='sigmoid') )


# 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,), activation='sigmoid') )

# 컴파일 해주렴
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [22]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1))

Epoch 1/10
1/1 [==============================] - 0s 19ms/step - loss: 0.6025 - accuracy: 0.5500
Epoch 2/10
1/1 [==============================] - 0s 20ms/step - loss: 0.6014 - accuracy: 0.5500
Epoch 3/10
1/1 [==============================] - 0s 22ms/step - loss: 0.6004 - accuracy: 0.5500
Epoch 4/10
1/1 [==============================] - 0s 19ms/step - loss: 0.5995 - accuracy: 0.5500
Epoch 5/10
1/1 [==============================] - 0s 21ms/step - loss: 0.5985 - accuracy: 0.5500
Epoch 6/10
1/1 [==============================] - 0s 15ms/step - loss: 0.5976 - accuracy: 0.5500
Epoch 7/10
1/1 [==============================] - 0s 14ms/step - loss: 0.5966 - accuracy: 0.5500
Epoch 8/10
1/1 [==============================] - 0s 14ms/step - loss: 0.5957 - accuracy: 0.5500
Epoch 9/10
1/1 [==============================] - 0s 12ms/step - loss: 0.5949 - accuracy: 0.5500
Epoch 10/10
1/1 [==============================] - 0s 12ms/step - loss: 0.5940 - accuracy: 0.5500
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 

## Now, Your turn!

In [23]:
# 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [24]:
x = np.array(range(40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [25]:
x.shape, y.shape

((40,), (40,))

In [28]:
## 모델링 : Sequential API
# 1. 세션 지우기
keras.backend.clear_session()

# 2. 모델 발판 만들기
model = keras.models.Sequential()

# 3. 모델 쌓기
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1, activation='sigmoid'))

# 4. 모델 컴파일
model.compile(loss='binary_crossentropy', metrics=['accuracy'], optimizer='adam')

In [32]:
a = model.fit(x, y, epochs=10)

Epoch 1/10
2/2 [==============================] - 0s 10ms/step - loss: 6.7971 - accuracy: 0.4750
Epoch 2/10
2/2 [==============================] - 0s 9ms/step - loss: 6.7667 - accuracy: 0.4750
Epoch 3/10
2/2 [==============================] - 0s 7ms/step - loss: 6.7377 - accuracy: 0.4750
Epoch 4/10
2/2 [==============================] - 0s 8ms/step - loss: 6.7062 - accuracy: 0.4750
Epoch 5/10
2/2 [==============================] - 0s 8ms/step - loss: 6.6759 - accuracy: 0.4750
Epoch 6/10
2/2 [==============================] - 0s 9ms/step - loss: 6.6441 - accuracy: 0.4750
Epoch 7/10
2/2 [==============================] - 0s 8ms/step - loss: 6.6144 - accuracy: 0.4750
Epoch 8/10
2/2 [==============================] - 0s 8ms/step - loss: 6.5838 - accuracy: 0.4750
Epoch 9/10
2/2 [==============================] - 0s 9ms/step - loss: 6.5528 - accuracy: 0.4750
Epoch 10/10
2/2 [==============================] - 0s 7ms/step - loss: 6.5243 - accuracy: 0.4750


In [31]:
y_pred = model.predict(x)
print(y_pred.reshape(-1)[:5])
print(y[:5])

2/2 [==============================] - 0s 5ms/step
[0.50489867 0.39212757 0.2898009  0.2051643  0.14036068]
[0 0 0 0 0]


In [33]:
a.history

{'loss': [6.7971086502075195,
  6.766702175140381,
  6.737718105316162,
  6.706185817718506,
  6.675880432128906,
  6.644112586975098,
  6.614392280578613,
  6.583813667297363,
  6.552787780761719,
  6.524275302886963],
 'accuracy': [0.4749999940395355,
  0.4749999940395355,
  0.4749999940395355,
  0.4749999940395355,
  0.4749999940395355,
  0.4749999940395355,
  0.4749999940395355,
  0.4749999940395355,
  0.4749999940395355,
  0.4749999940395355]}