# Keras로 Linear&Logistic Regression 맛보기!
---
#### 실습목표
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [2]:
x = np.array(range(20)) 
y = x * 2 - 1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [3]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 컴파일 해주렴
model.compile(loss='mse', optimizer='adam')

# 요약
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [4]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 828ms/step - loss: 1528.4741
Epoch 2/10
1/1 [==============================] - 0s 15ms/step - loss: 1527.5388
Epoch 3/10
1/1 [==============================] - 0s 19ms/step - loss: 1526.6042
Epoch 4/10
1/1 [==============================] - 0s 12ms/step - loss: 1525.6698
Epoch 5/10
1/1 [==============================] - 0s 11ms/step - loss: 1524.7358
Epoch 6/10
1/1 [==============================] - 0s 10ms/step - loss: 1523.8021
Epoch 7/10
1/1 [==============================] - 0s 14ms/step - loss: 1522.8684
Epoch 8/10
1/1 [==============================] - 0s 19ms/step - loss: 1521.9353
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 1521.0026
Epoch 10/10
1/1 [==============================] - 0s 10ms/step - loss: 1520.0701


In [5]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]
1/1 [==============================] - 0s 181ms/step
[ 9.9989027e-03 -1.5746132e+00 -3.1592255e+00 -4.7438378e+00
 -6.3284497e+00 -7.9130616e+00 -9.4976740e+00 -1.1082286e+01
 -1.2666898e+01 -1.4251510e+01 -1.5836122e+01 -1.7420734e+01
 -1.9005348e+01 -2.0589960e+01 -2.2174572e+01 -2.3759184e+01
 -2.5343796e+01 -2.6928408e+01 -2.8513020e+01 -3.0097631e+01]


## Now, Your turn!

In [6]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [7]:
x = np.array(range(20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [8]:
# 1. 세션 클리어
keras.backend.clear_session()

# 2. 엮기
input_layer = keras.layers.Input(shape=(1, ))
output_layer = keras.layers.Dense(1)(input_layer)

# 3. 모델 선언
model = keras.models.Model(input_layer, output_layer)

# 4. 컴파일
model.compile(loss='mse', optimizer='adam')

In [9]:
model.fit(x, y, epochs=10)

Epoch 1/10
1/1 [==============================] - 1s 521ms/step - loss: 688.5721
Epoch 2/10
1/1 [==============================] - 0s 11ms/step - loss: 687.9619
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 687.3521
Epoch 4/10
1/1 [==============================] - 0s 13ms/step - loss: 686.7425
Epoch 5/10
1/1 [==============================] - 0s 19ms/step - loss: 686.1332
Epoch 6/10
1/1 [==============================] - 0s 12ms/step - loss: 685.5242
Epoch 7/10
1/1 [==============================] - 0s 12ms/step - loss: 684.9156
Epoch 8/10
1/1 [==============================] - 0s 12ms/step - loss: 684.3073
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 683.6993
Epoch 10/10
1/1 [==============================] - 0s 12ms/step - loss: 683.0916


## Quick Logistic Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

In [ ]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)


# 컴파일 해주렴
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

## Now, Your turn!

In [10]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [11]:
x = np.array(range(40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [13]:
# 1. 세션 클리어
keras.backend.clear_session()

# 2. 엮기
il = keras.layers.Input(shape=(1, ))
ol = keras.layers.Dense(1, activation='sigmoid')(il)

# 3. 모델 선언
model = keras.models.Model(il, ol)

# 4. 컴파일
model.compile(loss='binary_crossentropy', optimizer='adam')

# 요약
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.fit(x, y, epochs=10)

Epoch 1/10
2/2 [==============================] - 1s 11ms/step - loss: 14.4322
Epoch 2/10
2/2 [==============================] - 0s 18ms/step - loss: 14.4025
Epoch 3/10
2/2 [==============================] - 0s 12ms/step - loss: 14.3720
Epoch 4/10
2/2 [==============================] - 0s 10ms/step - loss: 14.3430
Epoch 5/10
2/2 [==============================] - 0s 8ms/step - loss: 14.3128
Epoch 6/10
2/2 [==============================] - 0s 8ms/step - loss: 14.2831
Epoch 7/10
2/2 [==============================] - 0s 8ms/step - loss: 14.2529
Epoch 8/10
2/2 [==============================] - 0s 12ms/step - loss: 14.2241
Epoch 9/10
2/2 [==============================] - 0s 7ms/step - loss: 14.1926
Epoch 10/10
2/2 [==============================] - 0s 7ms/step - loss: 14.1623


In [18]:
y_pred = model.predict(x)
y_pred.reshape(-1)[:5]

2/2 [==============================] - 0s 6ms/step


array([0.504926  , 0.28147474, 0.13078669, 0.05463567, 0.02171609],
      dtype=float32)

In [19]:
y[:5]

array([0, 0, 0, 0, 0])