# 1일차 Review : 같은 문제 다시 풀어보기
---
- 학습은 10번만!

In [1]:
from sklearn.datasets import fetch_california_housing

In [2]:
california = fetch_california_housing()

In [3]:
x = california.data
y = california.target

In [4]:
x.shape, y.shape

((20640, 8), (20640,))

In [10]:
import pandas as pd

pd.DataFrame(x, columns=california.feature_names).head(2)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127    1.02381       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137    0.97188      2401.0  2.109842     37.86   

   Longitude  
0    -122.23  
1    -122.22

In [11]:
pd.DataFrame(y, columns=california.target_names).head(2)

MedHouseVal
0        4.526
1        3.585

In [5]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras

In [6]:
########
# 모델링
########
# 1. 세션 클리어
keras.backend.clear_session()

# 2. 모델 생성
model = keras.models.Sequential()

# 3. 모델 쌓기
model.add( keras.layers.Input(shape=(8,)) )
model.add( keras.layers.Dense(1) )

# 4. 모델 컴파일
model.compile(loss='mse', optimizer='adam')

In [7]:
###########
# 모델 학습
###########
model.fit(x, y, epochs=10)


Epoch 1/10
645/645 [==============================] - 1s 1ms/step - loss: 10666.9434
Epoch 2/10
645/645 [==============================] - 1s 1ms/step - loss: 439.7042
Epoch 3/10
645/645 [==============================] - 1s 1ms/step - loss: 135.9667
Epoch 4/10
645/645 [==============================] - 1s 1ms/step - loss: 81.1247
Epoch 5/10
645/645 [==============================] - 1s 1ms/step - loss: 73.2142
Epoch 6/10
645/645 [==============================] - 1s 2ms/step - loss: 67.8248
Epoch 7/10
645/645 [==============================] - 1s 2ms/step - loss: 62.5381
Epoch 8/10
645/645 [==============================] - 1s 1ms/step - loss: 56.9823
Epoch 9/10
645/645 [==============================] - 1s 1ms/step - loss: 54.3180
Epoch 10/10
645/645 [==============================] - 1s 1ms/step - loss: 47.4557


In [9]:
###########
# 모델 예측
###########
y_pred = model.predict(x)
print(y_pred.reshape(-1)[:5])
print(y[:5])

645/645 [==============================] - 1s 1ms/step
[4.9269514 2.5983453 5.8494177 3.4037538 2.6354036]
[4.526 3.585 3.521 3.413 3.422]


# 히든 레이어 추가하여 모델링!
---
- 조건
    - 히든 레이어 2개를 추가하여 다시 모델링!
    - 히든 레이어 노드 수 : 32
    - 히든 레이어 activation = 'relu'

In [17]:
########
# 모델링
########
# 1. 세션 초기화
keras.backend.clear_session()

# 2. 모델 생성
model = keras.models.Sequential()

# 3. 모델 쌓기
model.add( keras.layers.Input(shape=(8, )) )
model.add( keras.layers.Dense(32, activation='relu') )
model.add( keras.layers.Dense(32, activation='relu') )
model.add( keras.layers.Dense(1))

# 4. 모델 컴파일
model.compile(loss='mse', optimizer='adam')

# 모델 summary
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1,377
Trainable params: 1,377
Non-trainable params: 0
_________________________________________________________________


In [18]:
###########
# 모델 학습
###########
model.fit(x, y, epochs=10)

Epoch 1/10
645/645 [==============================] - 2s 2ms/step - loss: 8220.6719
Epoch 2/10
645/645 [==============================] - 1s 2ms/step - loss: 1.7661
Epoch 3/10
645/645 [==============================] - 1s 2ms/step - loss: 1.3383
Epoch 4/10
645/645 [==============================] - 1s 2ms/step - loss: 1.3984
Epoch 5/10
645/645 [==============================] - 1s 2ms/step - loss: 1.4061
Epoch 6/10
645/645 [==============================] - 1s 2ms/step - loss: 1.2035
Epoch 7/10
645/645 [==============================] - 1s 2ms/step - loss: 1.6264
Epoch 8/10
645/645 [==============================] - 1s 2ms/step - loss: 1.2157
Epoch 9/10
645/645 [==============================] - 1s 2ms/step - loss: 0.9977
Epoch 10/10
645/645 [==============================] - 1s 2ms/step - loss: 1.6151


In [19]:
###########
# 모델 예측
###########
y_pred = model.predict(x)
print(y_pred.reshape(-1)[:5])
print(y[:5])

645/645 [==============================] - 1s 1ms/step
[3.9733315 3.8935966 3.9155998 3.2563248 2.709385 ]
[4.526 3.585 3.521 3.413 3.422]
