# 1일차 Review : 같은 문제 다시 풀어보기
---
- 학습은 10번만!

In [64]:
from sklearn.datasets import load_iris

In [65]:
iris = load_iris()

In [66]:
x = iris.data
y = iris.target

In [67]:
x.shape, y.shape

((150, 4), (150,))

In [68]:
from sklearn.model_selection import train_test_split

In [69]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=2023)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((135, 4), (135,), (15, 4), (15,))

In [70]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras
from keras.utils import to_categorical
import numpy as np

In [71]:
class_n = len(np.unique(y_train))
class_n

3

In [72]:
#######################
# 어떤 전처리 작업 필요
# Hint : y.shape
#######################
y_train = to_categorical(y_train, class_n)
y_train.shape

(135, 3)

In [73]:
y_train[:5]

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [74]:
########
# 모델링
########
# 1. 세션 초기화
keras.backend.clear_session()

# 2. 모델 생성
model = keras.models.Sequential()

# 3. 모델 쌓기
model.add( keras.layers.Input(shape=(4, )) )
model.add( keras.layers.Dense(3, activation='softmax') )

# 4. 모델 컴파일
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

# 모델 summary
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [75]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 5ms/step - loss: 3.1606 - accuracy: 0.3185
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 3.0659 - accuracy: 0.3185
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 2.9748 - accuracy: 0.3185
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 2.8837 - accuracy: 0.3185
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 2.7927 - accuracy: 0.3185
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 2.7027 - accuracy: 0.3185
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 2.6178 - accuracy: 0.3185
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 2.5305 - accuracy: 0.3185
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 2.4470 - accuracy: 0.3185
Epoch 10/10
5/5 [==============================] - 0s 4ms/step - loss: 2.3668 - accuracy: 0.3185


In [76]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)
print(y_pred[:5])
print(y_test[:5])

1/1 [==============================] - 0s 43ms/step
[[0.00385255 0.9563832  0.03976424]
 [0.00409744 0.9212416  0.07466102]
 [0.00863804 0.9095431  0.08181882]
 [0.00127683 0.95670176 0.04202133]
 [0.00231049 0.9311176  0.06657187]]
[2 1 1 2 1]


In [77]:
print(np.array(list(map(lambda x: np.argmax(x), y_pred))))
print(y_test)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[2 1 1 2 1 2 1 1 0 1 0 1 0 2 0]


# 히든 레이어 추가하여 모델링! (Functional API)
---
- 조건
    - 히든 레이어 2개를 추가하여 다시 모델링!
    - 히든 레이어 노드 수 : 32
    - 히든 레이어 activation = 'relu'

In [82]:
########
# 모델링
########
# 1. 세션 초기화
keras.backend.clear_session()

# 2. 모델 생성
model = keras.models.Sequential()

# 3. 모델 쌓기
model.add( keras.layers.Input(shape=(4, )) )
model.add( keras.layers.Dense(32, activation='relu') )
model.add( keras.layers.Dense(32, activation='relu') )
model.add( keras.layers.Dense(3, activation='softmax') )

# 4. 모델 컴파일
model.compile(loss='categorical_crossentropy', metrics='accuracy', optimizer='adam')

# 모델 summary
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                160       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 3)                 99        
                                                                 
Total params: 1,315
Trainable params: 1,315
Non-trainable params: 0
_________________________________________________________________


In [83]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
5/5 [==============================] - 1s 3ms/step - loss: 1.0846 - accuracy: 0.3926
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.9802 - accuracy: 0.5852
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.8893 - accuracy: 0.7852
Epoch 4/10
5/5 [==============================] - 0s 4ms/step - loss: 0.8225 - accuracy: 0.6815
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.7772 - accuracy: 0.6889
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.7281 - accuracy: 0.6889
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.6885 - accuracy: 0.7630
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.6494 - accuracy: 0.8074
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.6059 - accuracy: 0.8296
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.5675 - accuracy: 0.8667


In [84]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)
print(y_pred[:5])
print(y_test[:5])

1/1 [==============================] - 0s 52ms/step
[[0.0554089  0.27997437 0.66461664]
 [0.17079999 0.4675564  0.36164355]
 [0.15405625 0.4424846  0.40345925]
 [0.05878104 0.33899164 0.6022274 ]
 [0.13536821 0.45920858 0.4054231 ]]
[2 1 1 2 1]


In [85]:
print(np.array(list(map(lambda x: np.argmax(x), y_pred))))
print(y_test)

[2 1 1 2 1 2 2 1 0 1 0 1 0 2 0]
[2 1 1 2 1 2 1 1 0 1 0 1 0 2 0]
